# Site settings

author: Team Hephy
email: team@teamhephy.com
twitter_username: teamhephy
github_username:  teamhephy
slack_inviter_url: https://slack.teamhephy.com

head-title: Team Hephy blogsite
title: Team Hephy

baseurl: "/blog"    # the subpath of your site, "/blog"
url: ""

# footer 
description: "Hephy Workflow is the open source fork of Deis Workflow."

favo: "Team Hephy blogsite comes online"
descrpt: "**Deis Workflow** is an open source Platform as a Service (PaaS) that adds a developer-friendly layer to any [Kubernetes][k8s-home] cluster, making it easy to deploy and manage applications."


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

